### ISSUE TITLE
add links to the badges

### ISSUE THREAD

**Issue by Umesh-01** [akshitadixit/VCallZer#39]
**Is your feature request related to a problem? Please describe.**
I think these badges should be linked to the related web pages present in README.md file, like now after clicking on them they are taking us to this type of web pages. 

![image](https://user-images.githubusercontent.com/83420185/122059290-1ad39200-ce0a-11eb-9a35-58fd6c6d115c.png)

This is of no use, it should contain the links to the related webpages/ sections. 

And also these badges are not looking enough good, I would like to align them to the center and make them all of single type.

![image](https://user-images.githubusercontent.com/83420185/122062244-deedfc00-ce0c-11eb-8d69-c1a0db78aac9.png)

**Describe the solution you'd like**
I would like to add links to these badges, align them to center, and make them all of single type.
For example, I will add a link to the PR badge so that a user can directly go to that webpage/section easily using the badge.

**Comment by Umesh-01** [comment]
@akshitadixit @jigar-sable Should I work on this??

**Comment by akshitadixit** [comment]
Hey @Umesh-01 I will still request you to drop in a sample screenshot of what changes you wish to make. Centering the badges - how'd that look for instance?

**Comment by Umesh-01** [comment]
@akshitadixit, check this out, hope it will explain... 

![image](https://user-images.githubusercontent.com/83420185/122508359-7fb40580-d01f-11eb-9652-093cf63c50c4.png)

**Comment by akshitadixit** [comment]
@Umesh-01 assigned
