### ISSUE TITLE
Want to make logo for VCallZer

### ISSUE THREAD

**Issue by ambivert-sam** [akshitadixit/VCallZer#40]
Want to contribute by making the logo for VCallZer I'm a participant of LGMSOC'21 can you please assign me this ?

**Comment by akshitadixit** [comment]
Cool @ambivert-sam assigned. Please let me know how much time will you need to work on this?

**Comment by ambivert-sam** [comment]
1-2 days

**Comment by ayushsoni1010** [comment]
Heyy @akshitadixit 

Can I also work on this issue ?

**Comment by akshitadixit** [comment]
@ayushsoni1010 we definitely cannot have 2 logos, but sure you can connect with @ambivert-sam on slack to collaborate and decide stuff.

**Comment by ambivert-sam** [comment]
> @ayushsoni1010 we definitely cannot have 2 logos, but sure you can connect with @ambivert-sam on slack to collaborate and decide stuff.

Sry @akshitadixit and @ayushsoni1010 I already completed the design
