### ISSUE TITLE
Add LGM-SOC'21 score card in readme.md

### ISSUE THREAD

**Issue by ishitakapoor26** [akshitadixit/VCallZer#44]
Add LGM-SOC'21 score card in readme.md

**Comment by ishitakapoor26** [comment]
@akshitadixit pls assign this issue to me.

**Comment by akshitadixit** [comment]
@ishitakapoor26 sure, but could you drop in a sample screenshot of what/how do you wish to add in?

**Comment by ishitakapoor26** [comment]
> @ishitakapoor26 sure, but could you drop in a sample screenshot of what/how do you wish to add in?

@akshitadixit i want to add this
![Uploading score card.PNG…]()

**Comment by ishitakapoor26** [comment]
> @ishitakapoor26 sure, but could you drop in a sample screenshot of what/how do you wish to add in?

@akshitadixit I want to add this
![score card](https://user-images.githubusercontent.com/78542333/122349655-12926880-cf6a-11eb-8eef-aacef19a636a.PNG)

**Comment by jigar-sable** [comment]
**That's visible when hover the labels.**

![image](https://user-images.githubusercontent.com/64949957/122514587-cc9cd980-d029-11eb-9622-1d3db9a30016.png)

**Comment by akshitadixit** [comment]
Thanks @jigar-sable 

@ishitakapoor26 this issue does not add value to the project. Closing it. Please feel free to contribute in other ways.
