### ISSUE TITLE
Add a to-do list section in the readme file

### ISSUE THREAD

**Issue by akshitadixit** [akshitadixit/VCallZer#6]
To keep track of incoming changes and work in progress, we will need a to-do section.
Add it in the readme and mention the issues currently setup as follows:

## TO-DO/In-progress:
- Adding documentation #2 
- Transfer audio over the connection #3 
.
.
And so on.

**Comment by hellosafwaan** [comment]
Please assign me this.

**Comment by akshitadixit** [comment]
@hellosafwaan sure :)
