### ISSUE TITLE
Add a new branch

### ISSUE THREAD

**Issue by akshitadixit** [akshitadixit/VCallZer#7]
For beginners.
Kindly add a new branch with the name web-app.
To create a new branch you need to open your git (from the bash, terminal, or vs-code, wherever you use it from) and follow these steps:
* `git checkout -b web-app` {to create a new branch and switch to it}
* `git rm -rf .` {to remove(rm) all files from the branch}
* Add a fresh README.md that specifies that this branch is for the webapp development
* `git add .`
* `git commit -m "Create new branch web-app"`
* `git push origin web-app`
* Then make a PR

**Comment by supzi-del** [comment]
Can you assign me this?

**Comment by akshitadixit** [comment]
@supzi-del sure :)

**Comment by ShivaSankeerth** [comment]
Hey @akshitadixit, is this issue still open? 

If it is open, I would like to work on it and can get it done by today itself.

**Comment by akshitadixit** [comment]
@ShivaSankeerth glad you wish to help, let's wait for @supzi-del and give her a fair chance at this?

**Comment by supzi-del** [comment]
https://github.com/akshitadixit/VCallZer/pull/11

Checkout the PR. Is it okay?

**Comment by ShivaSankeerth** [comment]
![image](https://user-images.githubusercontent.com/29270279/121530715-50980580-ca1b-11eb-9c94-ca54bec14428.png)

Hey @akshitadixit, can you check if the last merge has caused this?

**Comment by akshitadixit** [comment]
@ShivaSankeerth thank you so much for the warning, I did miss out the merge destination. Reverted the PR. You may make a new one please.

**Comment by supzi-del** [comment]
Hey! Sorry for the inconvienience.

**Comment by ShivaSankeerth** [comment]
Sure. I will work on it.

**Comment by akshitadixit** [comment]
> Hey! Sorry for the inconvienience.

It's completely okay. Git and GitHub are amazing and totally fault proof :)

**Comment by ShivaSankeerth** [comment]
Hey @akshitadixit , to which branch should I make the pull request to?

Can I do it to revert-11-web-app ?

**Comment by supzi-del** [comment]
I believe the new branch called web-app

**Comment by akshitadixit** [comment]
@supzi-del @ShivaSankeerth since your PRs were merged, do checkout #4
