### ISSUE TITLE
Update Readme file to help beginners contribute to open source 

### ISSUE THREAD

**Issue by Vedant-Jayesh-Oza** [akshitadixit/VCallZer#9]
Hello, I am a LGM-SOC'21 Participant
I am a Newbie coder And a beginner to open source contributions, I learnt open source contributions recently so I would like to update this Readme file where I will give some detailed steps to contribute to this project so that the Readme file can be more beginner friendly.
Assign this issue to me.

**Comment by Vedant-Jayesh-Oza** [comment]
@akshitadixit assign this issue to me I am LGM-SOC participant

**Comment by akshitadixit** [comment]
Sure!

**Comment by Vedant-Jayesh-Oza** [comment]
Ok thank you so much will start working on the issue 👍👍
